trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world, changed!
  displayName: 'Run a one-line script'
- task: TerraformTaskV3@3
  inputs:
    provider: 'aws'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/configuration/iaac/aws/kubernetes'
    backendServiceAWS: 'aws-for-terraform'
    backendAWSBucketName: 'terraform-backend-state-odiaby-123'
    backendAWSKey: 'kubernetes-dev.tfstate'

